import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen flex flex-col`}>
        <header className="bg-blue-600 text-white">
          <nav className="container mx-auto flex justify-between items-center py-4">
        <div className="text-lg font-semibold">
          <Link href="/">PaperMind</Link>
        </div>
        <div className="flex space-x-4">
          <Link href="/" className="hover:text-gray-200">
            Home
          </Link>
          <Link href="/predict" className="hover:text-gray-200">
            Predict
          </Link>
          <Link href="/recommend" className="hover:text-gray-200">
            Recommend
          </Link>
          <Link href="/questions" className="hover:text-gray-200">
            Questions
          </Link>
        </div>
          </nav>
        </header>
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
